language: ruby
rvm:
 - 2.5.1
cache:
- bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    secure: "T8jsyorPBK2PjftEpdjiyc3Op3Yv2UdDSv2qgIptL+BJD2XxikMi8TsOpLxV8/PEcRH+IZYyJgWeXBN65NGZl4dFM5GHZN8GrQ3bsyffPApL+MahLLK2K3NBc4lbQa9xyVzM9+5L0efotj1/cQ12EBEY2CyF5kdliMdFxOrizkWcaXCVCWB/LYFGgP9S0uKcU5silsrZzkiJzYgvxIU6TqGx9LvHJtPR62mP6+ugdgxiPlgMNtWkSJc9jP67UbGB0K8Nql0rEll91OvB9SEmkHHzt4y4hsUKa+Qm067/XjU82FP1OHQirT6+Q7QfAXCszqTSik+W3iQxEAEOzQ2nHObMiIMN6BKbQYuB8QQdO2F/QxOFLl+t3/FSRWGu5XYhRpljsY2lkKAyBQlMU+Xm0d9bpnabv9sybbseKPwQPW+73q3RwJ0o6/bmnq8IoUdsVK6SIeOodw+xRlw1GMclzWcmj+vo3Ivm85mmb+cx9jpZD/66zUuKTyhzKx/In5X3/JhAzNGL8bf+jo79uxeGmxTTLv1yKJKKv0gSQA9k9daKL01eXL2+cMnH/zbD0zZ249Hpe2tc3KmBsZFgSw+n8+41Dhwoa1QI0TPmiWsDSURzvVA0SHtuBAddr6YL27aU2NHCA75TTd1hsmaqe0ghra1lZHX3y9XZ6034XZ7TzP0="
  app: mighty-ravine-56690
  on:
    repo: emmaalbury/Team-Tela
